from .auth import router as auth_router
from .protected import router as protected_router
from .users import router as users_router
from .onboarding import router as onboarding_router
from .nutrition import router as nutrition_router
from .foods import router as foods_router
from .weights import router as weights_router
from .workouts import router as workouts_router
from .dashboard import router as dashboard_router
from .recipes import router as recipes_router
from .mealplans import router as mealplans_router
from .health import router as health_router
from .progress import router as progress_router
from .diary import router as diary_router
from .meal_plans import router as meal_plans_router
from .snap_meal import router as snap_meal_router
