"""add weight_entries

Revision ID: 415e03a1432e
Revises: 9143ba6f93d0
Create Date: 2025-09-26 15:50:07.395570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415e03a1432e'
down_revision: Union[str, Sequence[str], None] = '9143ba6f93d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_entries',
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index(op.f('ix_weight_entries_date'), 'weight_entries', ['date'], unique=False)
    op.create_index(op.f('ix_weight_entries_entry_id'), 'weight_entries', ['entry_id'], unique=False)
    op.create_index(op.f('ix_weight_entries_user_id'), 'weight_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weight_entries_user_id'), table_name='weight_entries')
    op.drop_index(op.f('ix_weight_entries_entry_id'), table_name='weight_entries')
    op.drop_index(op.f('ix_weight_entries_date'), table_name='weight_entries')
    op.drop_table('weight_entries')
    # ### end Alembic commands ###
