"""add workout_sessions and exercise_entries

Revision ID: 42014d645871
Revises: 60a5266d02bb
Create Date: 2025-09-28 20:12:02.788876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42014d645871'
down_revision: Union[str, Sequence[str], None] = '60a5266d02bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('workout_type', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_workout_sessions_date'), 'workout_sessions', ['date'], unique=False)
    op.create_index(op.f('ix_workout_sessions_session_id'), 'workout_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_table('exercise_entries',
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('exercise_name', sa.String(length=150), nullable=False),
    sa.Column('sets', sa.JSON(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index(op.f('ix_exercise_entries_entry_id'), 'exercise_entries', ['entry_id'], unique=False)
    op.create_index(op.f('ix_exercise_entries_exercise_name'), 'exercise_entries', ['exercise_name'], unique=False)
    op.create_index(op.f('ix_exercise_entries_session_id'), 'exercise_entries', ['session_id'], unique=False)
    op.create_index(op.f('ix_exercise_entries_user_id'), 'exercise_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_entries_user_id'), table_name='exercise_entries')
    op.drop_index(op.f('ix_exercise_entries_session_id'), table_name='exercise_entries')
    op.drop_index(op.f('ix_exercise_entries_exercise_name'), table_name='exercise_entries')
    op.drop_index(op.f('ix_exercise_entries_entry_id'), table_name='exercise_entries')
    op.drop_table('exercise_entries')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_session_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_date'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    # ### end Alembic commands ###
