"""update meal_plan

Revision ID: 4a4ffe6b5a4d
Revises: 79321bcd9a86
Create Date: 2026-01-02 15:49:08.081379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4ffe6b5a4d'
down_revision: Union[str, Sequence[str], None] = '79321bcd9a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plans', sa.Column('meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plans', 'meta')
    # ### end Alembic commands ###
