"""add workout_sessions and exercise_entries

Revision ID: 7625c2b125ea
Revises: 42014d645871
Create Date: 2025-09-30 00:32:16.408154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7625c2b125ea'
down_revision: Union[str, Sequence[str], None] = '42014d645871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise_entries', 'exercise_name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('exercise_entries', 'notes',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('exercise_entries_ibfk_1'), 'exercise_entries', type_='foreignkey')
    op.add_column('workout_sessions', sa.Column('name', sa.String(length=120), nullable=True))
    op.alter_column('workout_sessions', 'notes',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('workout_sessions', 'end_time')
    op.drop_column('workout_sessions', 'start_time')
    op.drop_column('workout_sessions', 'workout_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sessions', sa.Column('workout_type', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('workout_sessions', sa.Column('start_time', mysql.TIMESTAMP(), nullable=True))
    op.add_column('workout_sessions', sa.Column('end_time', mysql.TIMESTAMP(), nullable=True))
    op.alter_column('workout_sessions', 'notes',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
    op.drop_column('workout_sessions', 'name')
    op.create_foreign_key(op.f('exercise_entries_ibfk_1'), 'exercise_entries', 'workout_sessions', ['session_id'], ['session_id'])
    op.alter_column('exercise_entries', 'notes',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('exercise_entries', 'exercise_name',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
