"""init schema with onboarding

Revision ID: 875f76e1a583
Revises: 
Create Date: 2025-08-31 23:49:40.965840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875f76e1a583'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('exercise_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('target_muscles', sa.JSON(), nullable=True),
    sa.Column('equipment_needed', sa.JSON(), nullable=True),
    sa.Column('difficulty_level', sa.Enum('beginner', 'intermediate', 'advanced'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_index(op.f('ix_exercises_exercise_id'), 'exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_table('foods',
    sa.Column('food_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('serving_size_g', sa.String(length=10), nullable=True),
    sa.Column('calories', sa.SmallInteger(), nullable=True),
    sa.Column('protein_g', sa.String(length=10), nullable=True),
    sa.Column('carbs_g', sa.String(length=10), nullable=True),
    sa.Column('fat_g', sa.String(length=10), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_index(op.f('ix_foods_food_id'), 'foods', ['food_id'], unique=False)
    op.create_index(op.f('ix_foods_name'), 'foods', ['name'], unique=False)
    op.create_table('plans',
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('diet', 'workout'), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('duration_days', sa.SmallInteger(), nullable=True),
    sa.Column('target_goal', sa.String(length=50), nullable=True),
    sa.Column('plan_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=False)
    op.create_index(op.f('ix_plans_plan_id'), 'plans', ['plan_id'], unique=False)
    op.create_table('user_onboarding',
    sa.Column('user_onboarding_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('current_step', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_onboarding_id')
    )
    op.create_index(op.f('ix_user_onboarding_user_id'), 'user_onboarding', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_onboarding_user_onboarding_id'), 'user_onboarding', ['user_onboarding_id'], unique=False)
    op.create_table('user_plans',
    sa.Column('user_plan_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=28), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('progress_notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_plan_id')
    )
    op.create_index(op.f('ix_user_plans_user_plan_id'), 'user_plans', ['user_plan_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_enum'), nullable=True),
    sa.Column('height_cm', sa.SmallInteger(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('goal', sa.String(length=50), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('is_profile_complete', sa.Boolean(), nullable=False),
    sa.Column('onboarding_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_plans_user_plan_id'), table_name='user_plans')
    op.drop_table('user_plans')
    op.drop_index(op.f('ix_user_onboarding_user_onboarding_id'), table_name='user_onboarding')
    op.drop_index(op.f('ix_user_onboarding_user_id'), table_name='user_onboarding')
    op.drop_table('user_onboarding')
    op.drop_index(op.f('ix_plans_plan_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_foods_name'), table_name='foods')
    op.drop_index(op.f('ix_foods_food_id'), table_name='foods')
    op.drop_table('foods')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_exercise_id'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
