"""add food_entries table

Revision ID: a511cefd7ba5
Revises: 909c1fc71bd7
Create Date: 2025-09-15 17:34:19.641555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a511cefd7ba5'
down_revision: Union[str, Sequence[str], None] = '909c1fc71bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_entries',
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('consumed_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('food_api_id', sa.String(length=128), nullable=True),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fats_g', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index(op.f('ix_food_entries_date'), 'food_entries', ['date'], unique=False)
    op.create_index(op.f('ix_food_entries_entry_id'), 'food_entries', ['entry_id'], unique=False)
    op.create_index(op.f('ix_food_entries_meal_type'), 'food_entries', ['meal_type'], unique=False)
    op.create_index(op.f('ix_food_entries_user_id'), 'food_entries', ['user_id'], unique=False)
    op.drop_index(op.f('ix_exercises_exercise_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_foods_food_id'), table_name='foods')
    op.drop_index(op.f('ix_foods_name'), table_name='foods')
    op.drop_table('foods')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_plan_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_user_plans_user_plan_id'), table_name='user_plans')
    op.drop_table('user_plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_plans',
    sa.Column('user_plan_id', mysql.VARCHAR(length=26), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=28), nullable=False),
    sa.Column('plan_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('progress_notes', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('user_plan_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_plans_user_plan_id'), 'user_plans', ['user_plan_id'], unique=False)
    op.create_table('plans',
    sa.Column('plan_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type', mysql.ENUM('diet', 'workout'), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('duration_days', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('target_goal', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('plan_details', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('plan_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_plans_plan_id'), 'plans', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=False)
    op.create_table('foods',
    sa.Column('food_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('brand', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('serving_size_g', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('calories', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('protein_g', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('carbs_g', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('fat_g', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('tags', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('food_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_foods_name'), 'foods', ['name'], unique=False)
    op.create_index(op.f('ix_foods_food_id'), 'foods', ['food_id'], unique=False)
    op.create_table('exercises',
    sa.Column('exercise_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('target_muscles', mysql.JSON(), nullable=True),
    sa.Column('equipment_needed', mysql.JSON(), nullable=True),
    sa.Column('difficulty_level', mysql.ENUM('beginner', 'intermediate', 'advanced'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('exercise_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_index(op.f('ix_exercises_exercise_id'), 'exercises', ['exercise_id'], unique=False)
    op.drop_index(op.f('ix_food_entries_user_id'), table_name='food_entries')
    op.drop_index(op.f('ix_food_entries_meal_type'), table_name='food_entries')
    op.drop_index(op.f('ix_food_entries_entry_id'), table_name='food_entries')
    op.drop_index(op.f('ix_food_entries_date'), table_name='food_entries')
    op.drop_table('food_entries')
    # ### end Alembic commands ###
