"""update meal_plan

Revision ID: b5a21c54a3c3
Revises: 4a4ffe6b5a4d
Create Date: 2026-01-02 19:07:39.160807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b5a21c54a3c3'
down_revision: Union[str, Sequence[str], None] = '4a4ffe6b5a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plans', 'meta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plans', sa.Column('meta', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
