// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ4-3FAahBy1wtno7qqb5SwrCyBIyCLiY',
    appId: '1:738647177240:web:61356ebfddb82dcbc6ab6d',
    messagingSenderId: '738647177240',
    projectId: 'macromate-d84f5',
    authDomain: 'macromate-d84f5.firebaseapp.com',
    storageBucket: 'macromate-d84f5.firebasestorage.app',
    measurementId: 'G-RT394SCEGM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiZlZL9gkc8y6xvzreqIDtoeUJxbIHk7c',
    appId: '1:738647177240:ios:35a723020129c78fc6ab6d',
    messagingSenderId: '738647177240',
    projectId: 'macromate-d84f5',
    storageBucket: 'macromate-d84f5.firebasestorage.app',
    iosBundleId: 'com.example.onboarding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ4-3FAahBy1wtno7qqb5SwrCyBIyCLiY',
    appId: '1:738647177240:web:ccefb29129753d04c6ab6d',
    messagingSenderId: '738647177240',
    projectId: 'macromate-d84f5',
    authDomain: 'macromate-d84f5.firebaseapp.com',
    storageBucket: 'macromate-d84f5.firebasestorage.app',
    measurementId: 'G-94J809J5Z5',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiZlZL9gkc8y6xvzreqIDtoeUJxbIHk7c',
    appId: '1:738647177240:ios:35a723020129c78fc6ab6d',
    messagingSenderId: '738647177240',
    projectId: 'macromate-d84f5',
    storageBucket: 'macromate-d84f5.firebasestorage.app',
    iosBundleId: 'com.example.onboarding',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm3yca2drdGNHeIi6Ryd06tIaFxOkiWJE',
    appId: '1:738647177240:android:3908670c836b54f3c6ab6d',
    messagingSenderId: '738647177240',
    projectId: 'macromate-d84f5',
    storageBucket: 'macromate-d84f5.firebasestorage.app',
  );

}